buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
    id 'org.gauge' version '1.8.2'
    id 'com.browserstack.gradle-sdk' version '1.1.2'
}

group 'Gradle_example'
version '1.0-SNAPSHOT'

sourceCompatibility = 11
targetCompatibility = 11

repositories {
    mavenCentral()
}

configurations.all {
    resolutionStrategy {
        force 'com.google.guava:guava:30.1.1-jre'
                
            eachDependency { details -> 
                if (details.requested.group == 'com.google.guava') {
                    if (details.requested.name == 'guava') {
                        details.useVersion '30.1.1-jre'
                        details.because 'Compatibility with Java 11 and all dependencies'
                }
            }
        }
    }
}

dependencies {
    
    implementation('com.google.guava:guava:30.1.1-jre') {
        capabilities {
            requireCapability('com.google.guava:guava')
        }
    }
    implementation 'com.thoughtworks.gauge:gauge-java:0.12.0'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.20.2'
    implementation 'com.browserstack:browserstack-local-java:1.0.6'
    implementation 'org.seleniumhq.selenium:selenium-java:4.0.0'
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.browserstack:browserstack-java-sdk:latest.release'

}

gauge {
    specsDir = 'sample-specs/'
    additionalFlags = '--verbose'
}

// Task to run a single spec (add-to-cart only)
task runSingleSpec(type: com.thoughtworks.gauge.gradle.GaugeTask) {
    group = 'verification'
    description = 'Run only the add-to-cart spec file using Gauge'
    dependsOn 'testClasses'
    
    doFirst {
        project.gauge.specsDir = 'sample-specs/add-to-cart.spec'
    }
    
    doLast {
        project.gauge.specsDir = 'sample-specs/'
    }
}

// Task to run a single spec (add-to-cart only)
task runAllSpec(type: com.thoughtworks.gauge.gradle.GaugeTask) {
    group = 'verification'
    description = 'Run only the add-to-cart spec file using Gauge'
    dependsOn 'testClasses'
    
    doFirst {
        project.gauge.specsDir = 'sample-specs/'
    }
    
    doLast {
        project.gauge.specsDir = 'sample-specs/'
    }
}

// Task to run a single spec (add-to-cart only)
task runLocalSpec(type: com.thoughtworks.gauge.gradle.GaugeTask) {
    group = 'verification'
    description = 'Run only the add-to-cart spec file using Gauge'
    dependsOn 'testClasses'
    
    doFirst {
        project.gauge.specsDir = 'sample-local-specs/'
    }
    
    doLast {
        project.gauge.specsDir = 'sample-specs/'
    }
}