pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
    // resolutionStrategy {
    //     eachPlugin {
    //         if (requested.id.id == "org.gauge") {
    //             useModule("org.gauge:org.gauge.gradle.plugin:2.1.0")
    //         }
    //     }
    // }
}
rootProject.name = 'Gradle_example'

